name: wauble
recipe: wordpress
config:
  php: "8.2"
  webroot: wordpress
  via: nginx
  database: mysql
env_file:
  - .env
services:
  appserver:
    build_as_root:
      - "git config --global --add safe.directory /app"
      - "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\""
      - "php -r \"if (hash_file('sha384', 'composer-setup.php') === 'c8b085408188070d5f52bcfe4ecfbee5f727afa458b2573b8eaaf77b3419b0bf2768dc67c86944da1544f06fa544fd47') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }\""
      - "php composer-setup.php"
      - "php -r \"unlink('composer-setup.php');\""
      - "mv -f composer.phar /usr/local/bin/composer"
      - "curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
      - "chmod +x wp-cli.phar"
      # - "mv -f wp-cli.phar /usr/local/bin/wp"
      - "composer update"
      - "composer install"
      - "cd wordpress/wp-content/themes/wauble && composer install"
  node:
    type: node:22
    ports:
      - 5173:5173
    build:
      - "cd wordpress/wp-content/themes/wauble && npm install && npm run build"
  appserver_nginx:
    ssl: true
  pma:
    type: phpmyadmin
    hosts:
      - database
proxy:
  appserver_nginx:
    - wauble.lndo.site
  pma:
    - pma.wauble.lndo.site
tooling:
  node:
    service: node
  npm:
    service: node
  dev:
    service: node
    description: Start vite dev server
    cmd: cd /app/wordpress/wp-content/themes/wauble && npm run dev
  build:
    service: node
    description: Build theme with vite
    cmd: cd /app/wordpress/wp-content/themes/wauble && npm run build
  envoy:
    service: appserver
  composer:
    service: appserver
  setup:wordpress:
    service: appserver
    description: Install Wordpress noninteractively
    cmd:
      - wp core download --path=wordpress && wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database --path=wordpress --force
      - wp core install --url=http://wauble.lndo.site/ --title="wauble" --admin_user=admin --admin_password=password --admin_email=james.auble@gmail.com --path=wordpress
  setup:theme:
    service: appserver
    description: Download starter theme and install dependencies
    cmd:
      # - appserver: composer install
      - appserver: rm -rf wordpress/wp-content/themes/twentytwentythree
      - appserver: rm -rf wordpress/wp-content/themes/twentytwentyfour
      - appserver: cd wordpress/wp-content/themes/wauble && composer install
      - node: cd wordpress/wp-content/themes/wauble && npm install
      - node: cd wordpress/wp-content/themes/wauble && npm run build
      - appserver: wp theme activate wauble --path=wordpress
      - appserver: wp plugin delete hello --path=wordpress
      - appserver: wp plugin install --path=wordpress ./advanced-custom-fields-pro.zip
      - appserver: wp plugin activate --all --path=wordpress
      - appserver: wp option update page_on_front 2 --path=wordpress
      - appserver: wp option update show_on_front page --path=wordpress
      - appserver: wp menu create "Header Menu" --path=wordpress
      - appserver: wp menu location assign header-menu header-menu --path=wordpress
      - appserver: wp menu item add-post header-menu 2 --path=wordpress
      - appserver: wp menu create "Footer Menu" --path=wordpress
      - appserver: wp menu location assign footer-menu footer-menu --path=wordpress
      - appserver: wp menu item add-post footer-menu 2 --path=wordpress
      - appserver: wp --path=wordpress db query < .lando/wp-cli/setup-theme.sql
excludes:
  - wordpress/wp-content/themes/wauble/node_modules
  # - /app/wordpress/wp-content/themes/wauble/node_modules
  # - vendor
  # - wordpress/wp-content/themes/wauble/vendor
  # - wordpress/wp-content/uploads
