name: wauble
recipe: wordpress
config:
  php: '8.2'
  webroot: wordpress
  via: nginx
  database: mysql
  config:
    server: .lando/config/nginx.conf
env_file:
  - .env
# events:
#   pre-start:
#     - appserver: "cd $LANDO_MOUNT && composer install"
#     - appserver: "cd $LANDO_MOUNT/wordpress/wp-content/themes/wauble && composer install"
services:
  appserver:
    build_as_root:
      - "composer install"
      - "cd wordpress/wp-content/themes/wauble && composer install"
  appserver_nginx:
    ssl: true
    overrides:
      image: james0r/nginx
      ports:
      - 5173:5173
      volumes:
      - ./certs:/certs
    build_as_root:
      - mkdir -p /.npm
      - chown -R 501:33 "/.npm"
    build:
      - "cd wordpress/wp-content/themes/wauble && npm install && npm run build"
  pma:
    type: phpmyadmin
    hosts:
      - database
proxy:
  appserver_nginx:
    - wauble.lndo.site
  pma:
    - pma.wauble.lndo.site
tooling:
  node:
    service: appserver_nginx
  npm:
    service: appserver_nginx
  dev:
    service: appserver_nginx
    description: Start vite dev server
    cmd: cd wordpress/wp-content/themes/wauble && npm run dev
  build:
    service: appserver_nginx
    description: Build theme with vite
    cmd: cd wordpress/wp-content/themes/wauble && npm run build
  envoy:
    service: appserver
  composer:
    service: appserver
  setup:wordpress:
    service: appserver
    description: Install Wordpress noninteractively
    cmd:
      - wp core download --path=wordpress && wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database --path=wordpress --force
      - wp core install --url=http://wauble.lndo.site/ --title="wauble" --admin_user=admin --admin_password=password --admin_email=james.auble@gmail.com --path=wordpress
  setup:theme:
    service: appserver
    description: Download starter theme and install dependencies
    cmd:
      - appserver: composer install
      - appserver: rm -rf wordpress/wp-content/themes/twentytwentyone
      - appserver: rm -rf wordpress/wp-content/themes/twentytwentytwo
      - appserver: cd wordpress/wp-content/themes/wauble && composer install
      - node: cd wordpress/wp-content/themes/wauble && npm install
      - node: cd wordpress/wp-content/themes/wauble && npm run build
      - appserver: wp theme activate wauble --path=wordpress
      - appserver: wp plugin delete hello --path=wordpress
      - appserver: wp plugin activate --all --path=wordpress
      - appserver: wp option update page_on_front 2 --path=wordpress
      - appserver: wp option update show_on_front page --path=wordpress
      - appserver: wp menu create "Header Menu" --path=wordpress
      - appserver: wp menu location assign header-menu header_menu --path=wordpress
      - appserver: wp menu item add-post header-menu 2 --path=wordpress
      - appserver: wp menu create "Footer Menu" --path=wordpress
      - appserver: wp menu location assign footer-menu footer_menu --path=wordpress
      - appserver: wp menu item add-post footer-menu 2 --path=wordpress
excludes:
  - wordpress/wp-content/themes/wauble/node_modules
  # - /app/wordpress/wp-content/themes/wauble/node_modules
  # - vendor
  # - wordpress/wp-content/themes/wauble/vendor
  # - wordpress/wp-content/uploads