name: wauble-lando
recipe: wordpress
config:
  php: '8.2'
  webroot: wordpress
  via: nginx
  database: mysql
env_file:
  - .env
services:
  node:
    type: node:16
    services:
      ports:
        - 3000:3000
  pma:
    type: phpmyadmin
    hosts:
      - database
proxy:
  # Appserver_nginx or appserver for apache
  appserver_nginx:
    - wauble-lando.lndo.site
  pma:
    - pma.wauble-lando.lndo.site
tooling:
  npm:
    service: node
  node:
    service: node
  envoy:
    service: appserver
  composer:
    service: appserver
  setup:wordpress:
    service: appserver
    description: Install Wordpress noninteractively
    cmd:
      - wp core download --path=wordpress && wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database --path=wordpress
      - wp core install --url=https://wauble-lando.lndo.site/ --title="Wauble Lando" --admin_user=admin --admin_password=password --admin_email=james.auble@gmail.com --path=wordpress
      - wp option update page_on_front 2 --path=wordpress
      - wp option update show_on_front page --path=wordpress
  setup:environment:
    service: appserver
    description: Download starter theme and install dependencies
    cmd:
      - appserver: composer install
      - appserver: rm -rf wordpress/wp-content/themes/twentytwentyone
      - appserver: rm -rf wordpress/wp-content/themes/twentytwentytwo
      - appserver: mkdir -p wordpress/wp-content/themes/wauble
      - appserver: cd wordpress/wp-content/themes && git clone https://github.com/james0r/wauble.git temp && mv temp/* wauble/ && rm -rf temp
      - appserver: cd wordpress/wp-content/themes/wauble && composer install
      - node: cd wordpress/wp-content/themes/wauble && npm install
      - node: cd wordpress/wp-content/themes/wauble && npm run build
      - appserver: wp theme activate wauble --path=wordpress
      - appserver: wp plugin activate --all --path=wordpress
      - appserver: wp menu create "Header Menu" --path=wordpress
      - appserver: wp menu location assign header-menu header_menu --path=wordpress
      - appserver: wp menu item add-post header-menu 2 --path=wordpress
      - appserver: wp menu create "Footer Menu" --path=wordpress
      - appserver: wp menu location assign footer-menu footer_menu --path=wordpress
      - appserver: wp menu item add-post footer-menu 2 --path=wordpress
events:
  post-rebuild:
    - echo 'Post Rebuilt Triggered'
excludes:
  - vendor
  - wordpress/wp-content/themes/wauble/node_modules
  - wordpress/wp-content/themes/wauble/vendor
  # - wordpress/wp-content/uploads