<?php

// register_post_type( 'crb_services', array(
// 	'labels' => array(
// 		'name' => __( 'Services', 'crb' ),
// 		'singular_name' => __( 'Service', 'crb' ),
// 		'add_new' => __( 'Add New', 'crb' ),
// 		'add_new_item' => __( 'Add new service', 'crb' ),
// 		'view_item' => __( 'View Service', 'crb' ),
// 		'edit_item' => __( 'Edit Service', 'crb' ),
// 		'new_item' => __( 'New Service', 'crb' ),
// 		'view_item' => __( 'View Service', 'crb' ),
// 		'search_items' => __( 'Search Services', 'crb' ),
// 		'not_found' =>  __( 'No Services found', 'crb' ),
// 		'not_found_in_trash' => __( 'No Services found in trash', 'crb' ),
// 	),
// 	'public' => true,
// 	'exclude_from_search' => false,
// 	'show_ui' => true,
// 	'capability_type' => 'post',
// 	'hierarchical' => false,
// 	'_edit_link' => 'post.php?post=%d',
// 	'rewrite' => array(
// 		'slug' => 'service',
// 		'with_front' => false,
// 	),
// 	'query_var' => true,
// 	'menu_icon' => 'dashicons-admin-plugins',
// 	'supports' => array( 'title', 'editor', 'page-attributes', 'thumbnail', 'excerpt' ),
// ) );

// register_post_type( 'crb_projects', array(
// 	'labels' => array(
// 		'name' => __( 'Projects', 'crb' ),
// 		'singular_name' => __( 'Project', 'crb' ),
// 		'add_new' => __( 'Add New', 'crb' ),
// 		'add_new_item' => __( 'Add new project', 'crb' ),
// 		'view_item' => __( 'View Project', 'crb' ),
// 		'edit_item' => __( 'Edit Project', 'crb' ),
// 		'new_item' => __( 'New Project', 'crb' ),
// 		'view_item' => __( 'View Project', 'crb' ),
// 		'search_items' => __( 'Search Projects', 'crb' ),
// 		'not_found' =>  __( 'No Projects found', 'crb' ),
// 		'not_found_in_trash' => __( 'No Project found in trash', 'crb' ),
// 	),
// 	'public' => true,
// 	'exclude_from_search' => false,
// 	'show_ui' => true,
// 	'capability_type' => 'post',
// 	'hierarchical' => false,
// 	'_edit_link' => 'post.php?post=%d',
// 	'rewrite' => array(
// 		'slug' => 'service',
// 		'with_front' => false,
// 	),
// 	'query_var' => true,
// 	'menu_icon' => 'dashicons-portfolio',
//     'show_in_rest' => true,
//     'supports' => array( 'title', 'editor', 'page-attributes', 'thumbnail', 'excerpt' ),
// ) );