<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_629a2faa841fd',
	'title' => __('Social Links', 'wauble'),
	'fields' => array(
		array(
			'key' => 'field_629a2fb777e36',
			'label' => __('Facebook Link', 'wauble'),
			'name' => 'facebook_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => __('Leave blank to hide.', 'wauble'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_629a3063d54b8',
			'label' => __('Twitter Link', 'wauble'),
			'name' => 'twitter_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => __('Leave blank to hide.', 'wauble'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_629a308052147',
			'label' => __('Instagram Link', 'wauble'),
			'name' => 'instagram_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => __('Leave blank to hide.', 'wauble'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_63b21b26b2fe2',
			'label' => __('LinkedIn Link', 'wauble'),
			'name' => 'linkedin_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => __('Leave blank to hide.', 'wauble'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_63b21b51c1c65',
			'label' => __('Pinterest Link', 'wauble'),
			'name' => 'pinterest_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => __('Leave blank to hide.', 'wauble'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_629a30cd8c388',
			'label' => __('YouTube Link', 'wauble'),
			'name' => 'youtube_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => __('Leave blank to hide.', 'wauble'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'social-options',
			),
		),
	),
	'menu_order' => 3,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1689411982,
));

endif;