<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_643a1f50ed364',
	'title' => __('Sections', 'wauble'),
	'fields' => array(
		array(
			'key' => 'field_643a1f51f9c4b',
			'label' => __('Sections', 'wauble'),
			'name' => 'sections',
			'aria-label' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_6491495edb3c8' => array(
					'key' => 'layout_6491495edb3c8',
					'name' => 'posts_grid',
					'label' => __('Posts Grid', 'wauble'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6491496fdb3c9',
							'label' => __('Paginate', 'wauble'),
							'name' => 'paginate',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => __('If more than maximum posts, posts will be paginated.', 'wauble'),
							'default_value' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_64aa5198d9317',
							'label' => __('Use Global Posts Per Page', 'wauble'),
							'name' => 'use_global_posts_per_page',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_6491496fdb3c9',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => __('If enabled, the "Blog pages show at most" setting under Settings > Reading will be used.', 'wauble'),
							'default_value' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_649149b6f5e95',
							'label' => __('Max Posts Per Page', 'wauble'),
							'name' => 'max_posts_per_page',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_6491496fdb3c9',
										'operator' => '==',
										'value' => '1',
									),
									array(
										'field' => 'field_64aa5198d9317',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 8,
							'min' => -1,
							'max' => 24,
							'placeholder' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_649164428bd7d',
							'label' => __('Show Advanced Options', 'wauble'),
							'name' => 'show_advanced_options',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_64914d91c188d',
							'label' => __('Post Types', 'wauble'),
							'name' => 'post_type',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => __('If left empty, standard blog posts will be shown.', 'wauble'),
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_649164428bd7d',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'post' => 'post',
								'page' => 'page',
								'attachment' => 'attachment',
								'revision' => 'revision',
								'nav_menu_item' => 'nav_menu_item',
								'custom_css' => 'custom_css',
								'customize_changeset' => 'customize_changeset',
								'oembed_cache' => 'oembed_cache',
								'user_request' => 'user_request',
								'wp_block' => 'wp_block',
								'wp_template' => 'wp_template',
								'wp_template_part' => 'wp_template_part',
								'wp_global_styles' => 'wp_global_styles',
								'wp_navigation' => 'wp_navigation',
								'acf-post-type' => 'acf-post-type',
								'acf-taxonomy' => 'acf-taxonomy',
								'acf-field-group' => 'acf-field-group',
								'acf-field' => 'acf-field',
								'wpcf7_contact_form' => 'wpcf7_contact_form',
								'acfe-dbt' => 'acfe-dbt',
								'acfe-dpt' => 'acfe-dpt',
								'acfe-dt' => 'acfe-dt',
								'acfe-dop' => 'acfe-dop',
								'acfe-form' => 'acfe-form',
							),
							'default_value' => array(
							),
							'return_format' => 'value',
							'multiple' => 1,
							'allow_null' => 0,
							'ui' => 1,
							'ajax' => 0,
							'placeholder' => '',
							'allow_custom' => 0,
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_649150cdafd50',
							'label' => __('Categories', 'wauble'),
							'name' => 'categories',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => __('If left empty, all categories will be shown.', 'wauble'),
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_649164428bd7d',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'category',
							'add_term' => 0,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_64915265fbe46',
							'label' => __('Tags', 'wauble'),
							'name' => 'tags',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => __('If left empty, all tags will be shown.', 'wauble'),
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_649164428bd7d',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'post_tag',
							'add_term' => 0,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'multiple' => 0,
						),
						array(
							'key' => 'field_649178ea67190',
							'label' => __('Use AJAX', 'wauble'),
							'name' => 'use_ajax',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_649164428bd7d',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => __('Blog posts will be fetched without a complete page reload.', 'wauble'),
							'default_value' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_649acbdfa1a57',
							'label' => __('Show Categories on Posts', 'wauble'),
							'name' => 'show_categories_on_posts',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_649164428bd7d',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_649acdc99d204',
							'label' => __('Show Date on Posts', 'wauble'),
							'name' => 'show_date_on_posts',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_649164428bd7d',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_649e30d48a04b',
							'label' => __('Show Tags on Posts', 'wauble'),
							'name' => 'show_tags_on_posts',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_649164428bd7d',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_64acc8b767e8d' => array(
					'key' => 'layout_64acc8b767e8d',
					'name' => 'contact_form',
					'label' => __('Contact Form', 'wauble'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_64acc8ec67e8f',
							'label' => __('Heading', 'wauble'),
							'name' => 'heading',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => __('Leave blank to hide.', 'wauble'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => 'Contact Form Section',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_64acc945c8289',
							'label' => __('Description', 'wauble'),
							'name' => 'description',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => __('Leave blank to hide. NOTE: If this field does not load properly, it may be necessary to first Save/Update your page before the WYSIWYG editor will load properly.', 'wauble'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_64acc980624ed',
							'label' => __('Contact Form 7 Shortcode', 'wauble'),
							'name' => 'contact_form_7_shortcode',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => __('If left blank, the entire section will be hidden.', 'wauble'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '[contact-form-7 id="372" title="Contact form 1"]',
							'prepend' => '',
							'append' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_649edc3291577' => array(
					'key' => 'layout_649edc3291577',
					'name' => 'image_grid',
					'label' => __('Image Grid', 'wauble'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_649edcf6c0bd0',
							'label' => __('Heading', 'wauble'),
							'name' => 'heading',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_64a0ee825b71e',
							'label' => __('Enable Infinite Load More', 'wauble'),
							'name' => 'enable_infinite_load_more',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => __('When then last image in a group is in view, another group of images will fetched from the server and will appear in view.', 'wauble'),
							'default_value' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_64a12d6b319ad',
							'label' => __('Infinite Images in Group', 'wauble'),
							'name' => 'infinite_images_in_group',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_64a0ee825b71e',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 9,
							'min' => '',
							'max' => '',
							'placeholder' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_649fba2150513',
							'label' => __('Enable Lightbox', 'wauble'),
							'name' => 'enable_lightbox',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => __('If enabled, images are clickable and expand to fill the whole screen and operate as a gallery or "carousel".', 'wauble'),
							'default_value' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_649fb83735520',
							'label' => __('Enable Masonry Layout', 'wauble'),
							'name' => 'enable_masonry_layout',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => __('If enabled, images will retain aspect ratio and all available space will be used.', 'wauble'),
							'default_value' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_649fb8ac47ef8',
							'label' => __('Flow Direction', 'wauble'),
							'name' => 'flow_direction',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_649fb83735520',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Horizontal' => __('Horizontal', 'wauble'),
								'Vertical' => __('Vertical', 'wauble'),
							),
							'default_value' => 'Horizontal flows left-to-right, vertical flows top-to-bottom.',
							'return_format' => 'value',
							'allow_null' => 0,
							'other_choice' => 0,
							'layout' => 'horizontal',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_649edc4e91578',
							'label' => __('Images', 'wauble'),
							'name' => 'images',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'row',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => __('Add Row', 'wauble'),
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_649edc5991579',
									'label' => __('Image', 'wauble'),
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'uploader' => '',
									'acfe_thumbnail' => 0,
									'parent_repeater' => 'field_649edc4e91578',
								),
							),
							'acfe_repeater_stylised_button' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_643a1f595f9be' => array(
					'key' => 'layout_643a1f595f9be',
					'name' => 'content_area',
					'label' => __('Content Area', 'wauble'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_643a2a3af9c4c',
							'label' => __('Title', 'wauble'),
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_643a2a4ef9c4d',
							'label' => __('Content', 'wauble'),
							'name' => 'content',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'default_value' => '',
							'acfe_textarea_code' => 0,
							'maxlength' => '',
							'rows' => '',
							'placeholder' => '',
							'new_lines' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_643b1f1144a01' => array(
					'key' => 'layout_643b1f1144a01',
					'name' => 'front_page_demos',
					'label' => __('Front Page Demos', 'wauble'),
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_643b640b3d27a' => array(
					'key' => 'layout_643b640b3d27a',
					'name' => 'full_width_slider',
					'label' => __('Full-Width Slider', 'wauble'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_643b65bbae6db',
							'label' => __('Slides', 'wauble'),
							'name' => 'slides',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'row',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => __('Add Slide', 'wauble'),
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_643b65d0ae6dc',
									'label' => __('Image', 'wauble'),
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_save_meta' => 0,
									'uploader' => '',
									'return_format' => 'id',
									'acfe_thumbnail' => 0,
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'library' => 'all',
									'parent_repeater' => 'field_643b65bbae6db',
								),
								array(
									'key' => 'field_6485a07937aa0',
									'label' => __('Tint Image', 'wauble'),
									'name' => 'tint_image',
									'aria-label' => '',
									'type' => 'true_false',
									'instructions' => __('Applies a semi-opaque overlay over the slide image. When checked, opacity can be adjusted using the range slider below.', 'wauble'),
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'acfe_save_meta' => 0,
									'message' => '',
									'default_value' => 0,
									'acfe_settings' => '',
									'acfe_validate' => '',
									'ui_on_text' => '',
									'ui_off_text' => '',
									'ui' => 1,
									'parent_repeater' => 'field_643b65bbae6db',
								),
								array(
									'key' => 'field_6485a111e4df6',
									'label' => __('Tint Percentage', 'wauble'),
									'name' => 'tint_percentage',
									'aria-label' => '',
									'type' => 'range',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_6485a07937aa0',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => 30,
									'min' => 1,
									'max' => 99,
									'step' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_643b65bbae6db',
								),
								array(
									'key' => 'field_643b65dcae6dd',
									'label' => __('Heading', 'wauble'),
									'name' => 'heading',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_save_meta' => 0,
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_643b65bbae6db',
								),
							),
							'acfe_repeater_stylised_button' => 0,
						),
						array(
							'key' => 'field_64814f1bccc0f',
							'label' => __('Loop Slides', 'wauble'),
							'name' => 'loop_slides',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'message' => '',
							'default_value' => 1,
							'acfe_settings' => array(
								'6481503b08a56' => array(
									'acfe_settings_location' => '',
									'acfe_settings_settings' => '',
								),
							),
							'acfe_validate' => '',
							'acfe_permissions' => '',
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_6481649e6d133',
							'label' => __('Show Navigation', 'wauble'),
							'name' => 'show_navigation',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'message' => __('Show previous and next navigation buttons on top of slides.', 'wauble'),
							'default_value' => 1,
							'acfe_settings' => '',
							'acfe_validate' => '',
							'acfe_permissions' => '',
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_64816ee9c35b9',
							'label' => __('Show Pagination', 'wauble'),
							'name' => 'show_pagination',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'message' => __('Show dots representing the number of slides at the bottom of the slider.', 'wauble'),
							'default_value' => 0,
							'acfe_settings' => '',
							'acfe_validate' => '',
							'acfe_permissions' => '',
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_64ad2d789b0e1',
							'label' => __('Lazy Load Images', 'wauble'),
							'name' => 'lazy_load_images',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_6481a85ab42f1' => array(
					'key' => 'layout_6481a85ab42f1',
					'name' => 'faq',
					'label' => __('FAQ', 'wauble'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6481a8ee766aa',
							'label' => __('Use Global FAQ Items', 'wauble'),
							'name' => 'use_global_faq_items',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'message' => __('If enabled, FAQ items entered under FAQ in the main WordPress admin menu will be used.', 'wauble'),
							'default_value' => 0,
							'acfe_settings' => '',
							'acfe_validate' => '',
							'acfe_permissions' => '',
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_6481c398801d8',
							'label' => __('Only Allow 1 Item Expanded', 'wauble'),
							'name' => 'only_allow_1_item_expanded',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => __('If checked, this option will only allow one FAQ item to be expanded at a time.', 'wauble'),
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_6481a8ee766aa',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'message' => '',
							'default_value' => 0,
							'acfe_settings' => '',
							'acfe_validate' => '',
							'acfe_permissions' => '',
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_6481b47aaad88',
							'label' => __('Heading', 'wauble'),
							'name' => 'heading',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => __('Leave blank to hide.', 'wauble'),
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_6481a8ee766aa',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'default_value' => '',
							'acfe_settings' => '',
							'acfe_validate' => '',
							'maxlength' => '',
							'acfe_permissions' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6481a899b42f4',
							'label' => __('FAQ Items', 'wauble'),
							'name' => 'faq_items',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_6481a8ee766aa',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'acfe_repeater_stylised_button' => 1,
							'layout' => 'row',
							'acfe_settings' => '',
							'min' => 0,
							'max' => 0,
							'acfe_permissions' => '',
							'collapsed' => '',
							'button_label' => __('Add Row', 'wauble'),
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_6481a8c1b42f5',
									'label' => __('Question', 'wauble'),
									'name' => 'question',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_save_meta' => 0,
									'default_value' => '',
									'acfe_settings' => '',
									'acfe_validate' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_6481a899b42f4',
								),
								array(
									'key' => 'field_6481a8cab42f6',
									'label' => __('Answer', 'wauble'),
									'name' => 'answer',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_save_meta' => 0,
									'default_value' => '',
									'acfe_settings' => '',
									'acfe_validate' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
									'parent_repeater' => 'field_6481a899b42f4',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_648296afbe28f' => array(
					'key' => 'layout_648296afbe28f',
					'name' => '5050_image_split',
					'label' => __('50/50 Image Split', 'wauble'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_648296c2be290',
							'label' => __('Landscape Image', 'wauble'),
							'name' => 'landscape_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => __('Image should be landscape orientation dimensions with a minimum width of 1920 pixels.', 'wauble'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'uploader' => '',
							'return_format' => 'id',
							'acfe_thumbnail' => 0,
							'acfe_settings' => '',
							'acfe_validate' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'acfe_permissions' => '',
							'preview_size' => 'medium',
							'library' => 'all',
						),
						array(
							'key' => 'field_6482a7cac8642',
							'label' => __('Portrait Image', 'wauble'),
							'name' => 'portrait_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => __('If left blank, the landscape image will be used as a fallback. Portrait image should be portrait orientation dimensions with a minimum width of 1000 pixels.', 'wauble'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'uploader' => '',
							'return_format' => 'id',
							'acfe_thumbnail' => 0,
							'acfe_settings' => '',
							'acfe_validate' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'acfe_permissions' => '',
							'preview_size' => 'medium',
							'library' => 'all',
						),
						array(
							'key' => 'field_648297369f517',
							'label' => __('Image Position', 'wauble'),
							'name' => 'image_position',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'choices' => array(
								'Left' => __('Left', 'wauble'),
								'Right' => __('Right', 'wauble'),
							),
							'default_value' => 'Left',
							'return_format' => 'value',
							'acfe_settings' => '',
							'acfe_validate' => '',
							'allow_null' => 0,
							'other_choice' => 0,
							'acfe_permissions' => '',
							'layout' => 'horizontal',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_64829dca465a8',
							'label' => __('Tint Image', 'wauble'),
							'name' => 'tint_image',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'message' => __('Apply a tinted overlay over the image.', 'wauble'),
							'default_value' => 0,
							'acfe_settings' => '',
							'acfe_validate' => '',
							'acfe_permissions' => '',
							'ui_on_text' => '',
							'ui_off_text' => '',
							'ui' => 1,
						),
						array(
							'key' => 'field_64829e1d8d9ad',
							'label' => __('Tint Percentage', 'wauble'),
							'name' => 'tint_percentage',
							'aria-label' => '',
							'type' => 'range',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_64829dca465a8',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'default_value' => 30,
							'acfe_settings' => array(
								'64829e488d9ae' => array(
									'acfe_settings_location' => '',
									'acfe_settings_settings' => '',
								),
							),
							'acfe_validate' => array(
								'64829e518d9af' => array(
									'acfe_validate_location' => '',
									'acfe_validate_rules_and' => '',
									'acfe_validate_error' => '',
								),
							),
							'min' => 1,
							'max' => 99,
							'acfe_permissions' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6482a43572175',
							'label' => __('Heading', 'wauble'),
							'name' => 'heading',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => __('Leave blank to hide.', 'wauble'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'default_value' => '',
							'acfe_settings' => '',
							'acfe_validate' => '',
							'maxlength' => '',
							'acfe_permissions' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6482a45572176',
							'label' => __('Body Text', 'wauble'),
							'name' => 'body_text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => __('Leave blank to hide. NOTE: If this field does not load properly, it may be necessary to first Save/Update your page before the WYSIWYG editor will load properly.', 'wauble'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_6482ab04836fb',
							'label' => __('Content Vertical Align', 'wauble'),
							'name' => 'content_vertical_align',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'choices' => array(
								'Top' => __('Top', 'wauble'),
								'Middle' => __('Middle', 'wauble'),
								'Bottom' => __('Bottom', 'wauble'),
							),
							'default_value' => 'Bottom',
							'return_format' => 'value',
							'acfe_settings' => '',
							'acfe_validate' => '',
							'allow_null' => 0,
							'other_choice' => 0,
							'acfe_permissions' => '',
							'layout' => 'horizontal',
							'save_other_choice' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_649268c0e66d9' => array(
					'key' => 'layout_649268c0e66d9',
					'name' => 'tabs',
					'label' => __('Tabs', 'wauble'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_64926a1deacfe',
							'label' => __('Heading', 'wauble'),
							'name' => 'heading',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_649268cde66da',
							'label' => __('Tabs', 'wauble'),
							'name' => 'tabs',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'row',
							'min' => 2,
							'max' => 0,
							'collapsed' => '',
							'button_label' => __('Add Tab', 'wauble'),
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_64926902e66db',
									'label' => __('Label', 'wauble'),
									'name' => 'label',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_649268cde66da',
								),
								array(
									'key' => 'field_64926926e66dc',
									'label' => __('Panel Content', 'wauble'),
									'name' => 'panel_content',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'basic',
									'media_upload' => 1,
									'delay' => 0,
									'parent_repeater' => 'field_649268cde66da',
								),
							),
							'acfe_repeater_stylised_button' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_6492774bba1a0' => array(
					'key' => 'layout_6492774bba1a0',
					'name' => 'load_more',
					'label' => __('Load More', 'wauble'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6492783eaa848',
							'label' => __('Heading', 'wauble'),
							'name' => 'heading',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => __('Leave blank to hide.', 'wauble'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_649277988c0da',
							'label' => __('Items Per Group', 'wauble'),
							'name' => 'items_per_group',
							'aria-label' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 3,
							'min' => '',
							'max' => '',
							'placeholder' => '',
							'step' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_64927855cb74f',
							'label' => __('Load More Button Text', 'wauble'),
							'name' => 'load_more_button_text',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Load More',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_64927759ba1a1',
							'label' => __('Images', 'wauble'),
							'name' => 'images',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'row',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => __('Add Image', 'wauble'),
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_64927777ba1a2',
									'label' => __('Image', 'wauble'),
									'name' => 'image',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_64927759ba1a1',
									'uploader' => '',
									'acfe_thumbnail' => 0,
								),
							),
							'acfe_repeater_stylised_button' => 0,
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => __('Add Section', 'wauble'),
			'acfe_flexible_advanced' => false,
			'acfe_flexible_stylised_button' => false,
			'acfe_flexible_hide_empty_message' => false,
			'acfe_flexible_empty_message' => '',
			'acfe_flexible_layouts_templates' => false,
			'acfe_flexible_layouts_previews' => false,
			'acfe_flexible_layouts_placeholder' => false,
			'acfe_flexible_layouts_thumbnails' => false,
			'acfe_flexible_layouts_settings' => false,
			'acfe_flexible_async' => array(
			),
			'acfe_flexible_add_actions' => array(
			),
			'acfe_flexible_remove_button' => array(
			),
			'acfe_flexible_layouts_state' => false,
			'acfe_flexible_modal_edit' => array(
				'acfe_flexible_modal_edit_enabled' => false,
				'acfe_flexible_modal_edit_size' => 'large',
			),
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => false,
				'acfe_flexible_modal_title' => false,
				'acfe_flexible_modal_size' => 'full',
				'acfe_flexible_modal_col' => '4',
				'acfe_flexible_modal_categories' => false,
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array(
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'posts_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1689412049,
));

endif;